<?php

namespace Sat\Catalogos\Cfdi;

use Sat\Catalogos\Base;

class Aduana extends Base {
    protected static $db = [
        '01' => ['label' => 'ACAPULCO, ACAPULCO DE JUAREZ, GUERRERO.'],
        '47' => ['label' => 'AEROPUERTO INTERNACIONAL DE LA CIUDAD DE MEXICO,'],
        '02' => ['label' => 'AGUA PRIETA, AGUA PRIETA, SONORA.'],
        '73' => ['label' => 'AGUASCALIENTES, AGUASCALIENTES, AGUASCALIENTES.'],
        '81' => ['label' => 'ALTAMIRA, ALTAMIRA, TAMAULIPAS.'],
        '53' => ['label' => 'CANCUN, CANCUN, QUINTANA ROO.'],
        '67' => ['label' => 'CHIHUAHUA, CHIHUAHUA, CHIHUAHUA.'],
        '44' => ['label' => 'CIUDAD ACUÑA, CIUDAD ACUÑA, COAHUILA.'],
        '82' => ['label' => 'CIUDAD CAMARGO, CIUDAD CAMARGO, TAMAULIPAS.'],
        '06' => ['label' => 'CIUDAD DEL CARMEN, CIUDAD DEL CARMEN, CAMPECHE.'],
        '37' => ['label' => 'CIUDAD HIDALGO, CIUDAD HIDALGO, CHIAPAS.'],
        '07' => ['label' => 'CIUDAD JUAREZ, CIUDAD JUAREZ, CHIHUAHUA.'],
        '34' => ['label' => 'CIUDAD MIGUEL ALEMAN, CIUDAD MIGUEL ALEMAN, TAMAULIPAS.'],
        '30' => ['label' => 'CIUDAD REYNOSA, CIUDAD REYNOSA, TAMAULIPAS.'],
        '08' => ['label' => 'COATZACOALCOS, COATZACOALCOS, VERACRUZ.'],
        '80' => ['label' => 'COLOMBIA, COLOMBIA, NUEVO LEON.'],
        '83' => ['label' => 'DOS BOCAS, PARAISO, TABASCO.'],
        '11' => ['label' => 'ENSENADA, ENSENADA, BAJA CALIFORNIA.'],
        '48' => ['label' => 'GUADALAJARA, TLACOMULCO DE ZUÑIGA, JALISCO.'],
        '84' => ['label' => 'GUANAJUATO, SILAO, GUANAJUATO.'],
        '12' => ['label' => 'GUAYMAS, GUAYMAS, SONORA.'],
        '14' => ['label' => 'LA PAZ, LA PAZ, BAJA CALIFORNIA SUR.'],
        '51' => ['label' => 'LAZARO CARDENAS, LAZARO CARDENAS, MICHOACAN.'],
        '16' => ['label' => 'MANZANILLO, MANZANILLO, COLIMA.'],
        '17' => ['label' => 'MATAMOROS, MATAMOROS, TAMAULIPAS.'],
        '18' => ['label' => 'MAZATLAN, MAZATLAN, SINALOA.'],
        '19' => ['label' => 'MEXICALI, MEXICALI, BAJA CALIFORNIA.'],
        '20' => ['label' => 'MEXICO, DISTRITO FEDERAL.'],
        '52' => ['label' => 'MONTERREY, GENERAL MARIANO ESCOBEDO, NUEVO LEON.'],
        '22' => ['label' => 'NACO, NACO, SONORA.'],
        '23' => ['label' => 'NOGALES, NOGALES, SONORA.'],
        '24' => ['label' => 'NUEVO LAREDO, NUEVO LAREDO, TAMAULIPAS.'],
        '25' => ['label' => 'OJINAGA, OJINAGA, CHIHUAHUA.'],
        '27' => ['label' => 'PIEDRAS NEGRAS, PIEDRAS NEGRAS, COAHUILA.'],
        '28' => ['label' => 'PROGRESO, PROGRESO, YUCATAN.'],
        '75' => ['label' => 'PUEBLA, HEROICA PUEBLA DE ZARAGOZA, PUEBLA.'],
        '26' => ['label' => 'PUERTO PALOMAS, PUERTO PALOMAS, CHIHUAHUA.'],
        '64' => ['label' => 'QUERÉTARO, EL MARQUÉS Y COLON, QUERÉTARO.'],
        '31' => ['label' => 'SALINA CRUZ, SALINA CRUZ, OAXACA.'],
        '33' => ['label' => 'SAN LUIS RIO COLORADO, SAN LUIS RIO COLORADO, SONORA.'],
        '50' => ['label' => 'SONOYTA, SONOYTA, SONORA.'],
        '05' => ['label' => 'SUBTENIENTE LOPEZ, SUBTENIENTE LOPEZ, QUINTANA ROO.'],
        '38' => ['label' => 'TAMPICO, TAMPICO, TAMAULIPAS.'],
        '39' => ['label' => 'TECATE, TECATE, BAJA CALIFORNIA.'],
        '40' => ['label' => 'TIJUANA, TIJUANA, BAJA CALIFORNIA.'],
        '65' => ['label' => 'TOLUCA, TOLUCA, ESTADO DE MEXICO.'],
        '46' => ['label' => 'TORREON, TORREON, COAHUILA.'],
        '42' => ['label' => 'TUXPAN, TUXPAN DE RODRIGUEZ CANO, VERACRUZ.'],
        '43' => ['label' => 'VERACRUZ, VERACRUZ, VERACRUZ.'],
    ];
}