<?php

namespace Sat\Catalogos\Cfdi;

class Moneda extends \Sat\Catalogos\Base {
    protected static $db = [
        'AED' => ['label' => 'Dirham de EAU', 'decimales' => '2', 'variacion' => '35 %'],
        'AFN' => ['label' => 'Afghani', 'decimales' => '2', 'variacion' => '35 %'],
        'ALL' => ['label' => 'Lek', 'decimales' => '2', 'variacion' => '35 %'],
        'AMD' => ['label' => 'Dram armenio', 'decimales' => '2', 'variacion' => '35 %'],
        'ANG' => ['label' => 'Florín antillano neerlandés', 'decimales' => '2', 'variacion' => '35 %'],
        'AOA' => ['label' => 'Kwanza', 'decimales' => '2', 'variacion' => '35 %'],
        'ARS' => ['label' => 'Peso Argentino', 'decimales' => '2', 'variacion' => '63 %'],
        'AUD' => ['label' => 'Dólar Australiano', 'decimales' => '2', 'variacion' => '44 %'],
        'AWG' => ['label' => 'Aruba Florin', 'decimales' => '2', 'variacion' => '35 %'],
        'AZN' => ['label' => 'Azerbaijanian Manat', 'decimales' => '2', 'variacion' => '35 %'],
        'BAM' => ['label' => 'Convertibles marca', 'decimales' => '2', 'variacion' => '35 %'],
        'BBD' => ['label' => 'Dólar de Barbados', 'decimales' => '2', 'variacion' => '35 %'],
        'BDT' => ['label' => 'Taka', 'decimales' => '2', 'variacion' => '35 %'],
        'BGN' => ['label' => 'Lev búlgaro', 'decimales' => '2', 'variacion' => '35 %'],
        'BHD' => ['label' => 'Dinar de Bahrein', 'decimales' => '3', 'variacion' => '35 %'],
        'BIF' => ['label' => 'Burundi Franc', 'decimales' => '0', 'variacion' => '35 %'],
        'BMD' => ['label' => 'Dólar de Bermudas', 'decimales' => '2', 'variacion' => '35 %'],
        'BND' => ['label' => 'Dólar de Brunei', 'decimales' => '2', 'variacion' => '35 %'],
        'BOB' => ['label' => 'Boliviano', 'decimales' => '2', 'variacion' => '35 %'],
        'BOV' => ['label' => 'Mvdol', 'decimales' => '2', 'variacion' => '35 %'],
        'BRL' => ['label' => 'Real brasileño', 'decimales' => '2', 'variacion' => '51 %'],
        'BSD' => ['label' => 'Dólar de las Bahamas', 'decimales' => '2', 'variacion' => '35 %'],
        'BTN' => ['label' => 'Ngultrum', 'decimales' => '2', 'variacion' => '35 %'],
        'BWP' => ['label' => 'Pula', 'decimales' => '2', 'variacion' => '35 %'],
        'BYR' => ['label' => 'Rublo bielorruso', 'decimales' => '0', 'variacion' => '35 %'],
        'BZD' => ['label' => 'Dólar de Belice', 'decimales' => '2', 'variacion' => '36 %'],
        'CAD' => ['label' => 'Dolar Canadiense', 'decimales' => '2', 'variacion' => '31 %'],
        'CDF' => ['label' => 'Franco congoleño', 'decimales' => '2', 'variacion' => '35 %'],
        'CHE' => ['label' => 'WIR Euro', 'decimales' => '2', 'variacion' => '35 %'],
        'CHF' => ['label' => 'Franco Suizo', 'decimales' => '2', 'variacion' => '49 %'],
        'CHW' => ['label' => 'Franc WIR', 'decimales' => '2', 'variacion' => '35 %'],
        'CLF' => ['label' => 'Unidad de Fomento', 'decimales' => '4', 'variacion' => '35 %'],
        'CLP' => ['label' => 'Peso chileno', 'decimales' => '0', 'variacion' => '45 %'],
        'CNY' => ['label' => 'Yuan Renminbi', 'decimales' => '2', 'variacion' => '28 %'],
        'COP' => ['label' => 'Peso Colombiano', 'decimales' => '2', 'variacion' => '33 %'],
        'COU' => ['label' => 'Unidad de Valor real', 'decimales' => '2', 'variacion' => '35 %'],
        'CRC' => ['label' => 'Colón costarricense', 'decimales' => '2', 'variacion' => '31 %'],
        'CUC' => ['label' => 'Peso Convertible', 'decimales' => '2', 'variacion' => '35 %'],
        'CUP' => ['label' => 'Peso Cubano', 'decimales' => '2', 'variacion' => '36 %'],
        'CVE' => ['label' => 'Cabo Verde Escudo', 'decimales' => '2', 'variacion' => '35 %'],
        'CZK' => ['label' => 'Corona checa', 'decimales' => '2', 'variacion' => '42 %'],
        'DJF' => ['label' => 'Franco de Djibouti', 'decimales' => '0', 'variacion' => '35 %'],
        'DKK' => ['label' => 'Corona danesa', 'decimales' => '2', 'variacion' => '40 %'],
        'DOP' => ['label' => 'Peso Dominicano', 'decimales' => '2', 'variacion' => '51 %'],
        'DZD' => ['label' => 'Dinar argelino', 'decimales' => '2', 'variacion' => '30 %'],
        'EGP' => ['label' => 'Libra egipcia', 'decimales' => '2', 'variacion' => '34 %'],
        'ERN' => ['label' => 'Nakfa', 'decimales' => '2', 'variacion' => '35 %'],
        'ETB' => ['label' => 'Birr etíope', 'decimales' => '2', 'variacion' => '35 %'],
        'EUR' => ['label' => 'Euro', 'decimales' => '2', 'variacion' => '40 %'],
        'FJD' => ['label' => 'Dólar de Fiji', 'decimales' => '2', 'variacion' => '35 %'],
        'FKP' => ['label' => 'Libra malvinense', 'decimales' => '2', 'variacion' => '35 %'],
        'GBP' => ['label' => 'Libra Esterlina', 'decimales' => '2', 'variacion' => '29 %'],
        'GEL' => ['label' => 'Lari', 'decimales' => '2', 'variacion' => '35 %'],
        'GHS' => ['label' => 'Cedi de Ghana', 'decimales' => '2', 'variacion' => '35 %'],
        'GIP' => ['label' => 'Libra de Gibraltar', 'decimales' => '2', 'variacion' => '35 %'],
        'GMD' => ['label' => 'Dalasi', 'decimales' => '2', 'variacion' => '35 %'],
        'GNF' => ['label' => 'Franco guineano', 'decimales' => '0', 'variacion' => '35 %'],
        'GTQ' => ['label' => 'Quetzal', 'decimales' => '2', 'variacion' => '36 %'],
        'GYD' => ['label' => 'Dólar guyanés', 'decimales' => '2', 'variacion' => '35 %'],
        'HKD' => ['label' => 'Dolar De Hong Kong', 'decimales' => '2', 'variacion' => '35 %'],
        'HNL' => ['label' => 'Lempira', 'decimales' => '2', 'variacion' => '28 %'],
        'HRK' => ['label' => 'Kuna', 'decimales' => '2', 'variacion' => '35 %'],
        'HTG' => ['label' => 'Gourde', 'decimales' => '2', 'variacion' => '35 %'],
        'HUF' => ['label' => 'Florín', 'decimales' => '2', 'variacion' => '38 %'],
        'IDR' => ['label' => 'Rupia', 'decimales' => '2', 'variacion' => '35 %'],
        'ILS' => ['label' => 'Nuevo Shekel Israelí', 'decimales' => '2', 'variacion' => '33 %'],
        'INR' => ['label' => 'Rupia india', 'decimales' => '2', 'variacion' => '30 %'],
        'IQD' => ['label' => 'Dinar iraquí', 'decimales' => '3', 'variacion' => '59 %'],
        'IRR' => ['label' => 'Rial iraní', 'decimales' => '2', 'variacion' => '35 %'],
        'ISK' => ['label' => 'Corona islandesa', 'decimales' => '0', 'variacion' => '35 %'],
        'JMD' => ['label' => 'Dólar Jamaiquino', 'decimales' => '2', 'variacion' => '28 %'],
        'JOD' => ['label' => 'Dinar jordano', 'decimales' => '3', 'variacion' => '35 %'],
        'JPY' => ['label' => 'Yen', 'decimales' => '0', 'variacion' => '57 %'],
        'KES' => ['label' => 'Chelín keniano', 'decimales' => '2', 'variacion' => '30 %'],
        'KGS' => ['label' => 'Som', 'decimales' => '2', 'variacion' => '35 %'],
        'KHR' => ['label' => 'Riel', 'decimales' => '2', 'variacion' => '35 %'],
        'KMF' => ['label' => 'Franco Comoro', 'decimales' => '0', 'variacion' => '35 %'],
        'KPW' => ['label' => 'Corea del Norte ganó', 'decimales' => '2', 'variacion' => '35 %'],
        'KRW' => ['label' => 'Won', 'decimales' => '0', 'variacion' => '35 %'],
        'KWD' => ['label' => 'Dinar kuwaití', 'decimales' => '3', 'variacion' => '33 %'],
        'KYD' => ['label' => 'Dólar de las Islas Caimán', 'decimales' => '2', 'variacion' => '35 %'],
        'KZT' => ['label' => 'Tenge', 'decimales' => '2', 'variacion' => '35 %'],
        'LAK' => ['label' => 'Kip', 'decimales' => '2', 'variacion' => '35 %'],
        'LBP' => ['label' => 'Libra libanesa', 'decimales' => '2', 'variacion' => '35 %'],
        'LKR' => ['label' => 'Rupia de Sri Lanka', 'decimales' => '2', 'variacion' => '35 %'],
        'LRD' => ['label' => 'Dólar liberiano', 'decimales' => '2', 'variacion' => '35 %'],
        'LSL' => ['label' => 'Loti', 'decimales' => '2', 'variacion' => '35 %'],
        'LYD' => ['label' => 'Dinar libio', 'decimales' => '3', 'variacion' => '35 %'],
        'MAD' => ['label' => 'Dirham marroquí', 'decimales' => '2', 'variacion' => '36 %'],
        'MDL' => ['label' => 'Leu moldavo', 'decimales' => '2', 'variacion' => '35 %'],
        'MGA' => ['label' => 'Ariary malgache', 'decimales' => '2', 'variacion' => '35 %'],
        'MKD' => ['label' => 'Denar', 'decimales' => '2', 'variacion' => '35 %'],
        'MMK' => ['label' => 'Kyat', 'decimales' => '2', 'variacion' => '35 %'],
        'MNT' => ['label' => 'Tugrik', 'decimales' => '2', 'variacion' => '35 %'],
        'MOP' => ['label' => 'Pataca', 'decimales' => '2', 'variacion' => '35 %'],
        'MRO' => ['label' => 'Ouguiya', 'decimales' => '2', 'variacion' => '35 %'],
        'MUR' => ['label' => 'Rupia de Mauricio', 'decimales' => '2', 'variacion' => '35 %'],
        'MVR' => ['label' => 'Rupia', 'decimales' => '2', 'variacion' => '35 %'],
        'MWK' => ['label' => 'Kwacha', 'decimales' => '2', 'variacion' => '35 %'],
        'MXN' => ['label' => 'Peso Mexicano', 'decimales' => '2', 'variacion' => '35 %'],
        'MXV' => ['label' => 'México Unidad de Inversión (UDI)', 'decimales' => '2', 'variacion' => '35 %'],
        'MYR' => ['label' => 'Ringgit malayo', 'decimales' => '2', 'variacion' => '27 %'],
        'MZN' => ['label' => 'Mozambique Metical', 'decimales' => '2', 'variacion' => '35 %'],
        'NAD' => ['label' => 'Dólar de Namibia', 'decimales' => '2', 'variacion' => '35 %'],
        'NGN' => ['label' => 'Naira', 'decimales' => '2', 'variacion' => '31 %'],
        'NIO' => ['label' => 'Córdoba Oro', 'decimales' => '2', 'variacion' => '35 %'],
        'NOK' => ['label' => 'Corona noruega', 'decimales' => '2', 'variacion' => '34 %'],
        'NPR' => ['label' => 'Rupia nepalí', 'decimales' => '2', 'variacion' => '35 %'],
        'NZD' => ['label' => 'Dólar de Nueva Zelanda', 'decimales' => '2', 'variacion' => '45 %'],
        'OMR' => ['label' => 'Rial omaní', 'decimales' => '3', 'variacion' => '35 %'],
        'PAB' => ['label' => 'Balboa', 'decimales' => '2', 'variacion' => '35 %'],
        'PEN' => ['label' => 'Nuevo Sol', 'decimales' => '2', 'variacion' => '29 %'],
        'PGK' => ['label' => 'Kina', 'decimales' => '2', 'variacion' => '35 %'],
        'PHP' => ['label' => 'Peso filipino', 'decimales' => '2', 'variacion' => '30 %'],
        'PKR' => ['label' => 'Rupia de Pakistán', 'decimales' => '2', 'variacion' => '35 %'],
        'PLN' => ['label' => 'Zloty', 'decimales' => '2', 'variacion' => '39 %'],
        'PYG' => ['label' => 'Guaraní', 'decimales' => '0', 'variacion' => '37 %'],
        'QAR' => ['label' => 'Qatar Rial', 'decimales' => '2', 'variacion' => '35 %'],
        'RON' => ['label' => 'Leu rumano', 'decimales' => '2', 'variacion' => '36 %'],
        'RSD' => ['label' => 'Dinar serbio', 'decimales' => '2', 'variacion' => '35 %'],
        'RUB' => ['label' => 'Rublo ruso', 'decimales' => '2', 'variacion' => '35 %'],
        'RWF' => ['label' => 'Franco ruandés', 'decimales' => '0', 'variacion' => '35 %'],
        'SAR' => ['label' => 'Riyal saudí', 'decimales' => '2', 'variacion' => '35 %'],
        'SBD' => ['label' => 'Dólar de las Islas Salomón', 'decimales' => '2', 'variacion' => '35 %'],
        'SCR' => ['label' => 'Rupia de Seychelles', 'decimales' => '2', 'variacion' => '35 %'],
        'SDG' => ['label' => 'Libra sudanesa', 'decimales' => '2', 'variacion' => '35 %'],
        'SEK' => ['label' => 'Corona sueca', 'decimales' => '2', 'variacion' => '38 %'],
        'SGD' => ['label' => 'Dolar De Singapur', 'decimales' => '2', 'variacion' => '35 %'],
        'SHP' => ['label' => 'Libra de Santa Helena', 'decimales' => '2', 'variacion' => '35 %'],
        'SLL' => ['label' => 'Leona', 'decimales' => '2', 'variacion' => '35 %'],
        'SOS' => ['label' => 'Chelín somalí', 'decimales' => '2', 'variacion' => '35 %'],
        'SRD' => ['label' => 'Dólar de Suriname', 'decimales' => '2', 'variacion' => '35 %'],
        'SSP' => ['label' => 'Libra sudanesa Sur', 'decimales' => '2', 'variacion' => '35 %'],
        'STD' => ['label' => 'Dobra', 'decimales' => '2', 'variacion' => '35 %'],
        'SVC' => ['label' => 'Colon El Salvador', 'decimales' => '2', 'variacion' => '35 %'],
        'SYP' => ['label' => 'Libra Siria', 'decimales' => '2', 'variacion' => '35 %'],
        'SZL' => ['label' => 'Lilangeni', 'decimales' => '2', 'variacion' => '35 %'],
        'THB' => ['label' => 'Baht', 'decimales' => '2', 'variacion' => '37 %'],
        'TJS' => ['label' => 'Somoni', 'decimales' => '2', 'variacion' => '35 %'],
        'TMT' => ['label' => 'Turkmenistán nuevo manat', 'decimales' => '2', 'variacion' => '35 %'],
        'TND' => ['label' => 'Dinar tunecino', 'decimales' => '3', 'variacion' => '35 %'],
        'TOP' => ['label' => 'Pa\'anga', 'decimales' => '2', 'variacion' => '35 %'],
        'TRY' => ['label' => 'Lira turca', 'decimales' => '2', 'variacion' => '35 %'],
        'TTD' => ['label' => 'Dólar de Trinidad y Tobago', 'decimales' => '2', 'variacion' => '29 %'],
        'TWD' => ['label' => 'Nuevo dólar de Taiwán', 'decimales' => '2', 'variacion' => '30 %'],
        'TZS' => ['label' => 'Shilling tanzano', 'decimales' => '2', 'variacion' => '35 %'],
        'UAH' => ['label' => 'Hryvnia', 'decimales' => '2', 'variacion' => '51 %'],
        'UGX' => ['label' => 'Shilling de Uganda', 'decimales' => '0', 'variacion' => '35 %'],
        'USD' => ['label' => 'Dolar americano', 'decimales' => '2', 'variacion' => '35 %'],
        'USN' => ['label' => 'Dólar estadounidense (día siguiente)', 'decimales' => '2', 'variacion' => '35 %'],
        'UYI' => ['label' => 'Peso Uruguay en Unidades Indexadas (URUIURUI)', 'decimales' => '0', 'variacion' => '35 %'],
        'UYU' => ['label' => 'Peso Uruguayo', 'decimales' => '2', 'variacion' => '32 %'],
        'UZS' => ['label' => 'Uzbekistán Sum', 'decimales' => '2', 'variacion' => '35 %'],
        'VEF' => ['label' => 'Bolívar', 'decimales' => '2', 'variacion' => '153 %'],
        'VND' => ['label' => 'Dong', 'decimales' => '0', 'variacion' => '30 %'],
        'VUV' => ['label' => 'Vatu', 'decimales' => '0', 'variacion' => '35 %'],
        'WST' => ['label' => 'Tala', 'decimales' => '2', 'variacion' => '35 %'],
        'XAF' => ['label' => 'Franco CFA BEAC', 'decimales' => '0', 'variacion' => '35 %'],
        'XAG' => ['label' => 'Plata', 'decimales' => '0', 'variacion' => '35 %'],
        'XAU' => ['label' => 'Oro', 'decimales' => '0', 'variacion' => '35 %'],
        'XBA' => ['label' => 'Unidad de Mercados de Bonos Unidad Europea Composite (EURCO)', 'decimales' => '0', 'variacion' => '35 %'],
        'XBB' => ['label' => 'Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6)', 'decimales' => '0', 'variacion' => '35 %'],
        'XBC' => ['label' => 'Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9)', 'decimales' => '0', 'variacion' => '35 %'],
        'XBD' => ['label' => 'Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17)', 'decimales' => '0', 'variacion' => '35 %'],
        'XCD' => ['label' => 'Dólar del Caribe Oriental', 'decimales' => '2', 'variacion' => '35 %'],
        'XDR' => ['label' => 'DEG (Derechos Especiales de Giro)', 'decimales' => '0', 'variacion' => '37 %'],
        'XOF' => ['label' => 'Franco CFA BCEAO', 'decimales' => '0', 'variacion' => '35 %'],
        'XPD' => ['label' => 'Paladio', 'decimales' => '0', 'variacion' => '35 %'],
        'XPF' => ['label' => 'Franco CFP', 'decimales' => '0', 'variacion' => '35 %'],
        'XPT' => ['label' => 'Platino', 'decimales' => '0', 'variacion' => '35 %'],
        'XSU' => ['label' => 'Sucre', 'decimales' => '0', 'variacion' => '35 %'],
        'XTS' => ['label' => 'Códigos reservados específicamente para propósitos de prueba', 'decimales' => '0', 'variacion' => null],
        'XUA' => ['label' => 'Unidad ADB de Cuenta', 'decimales' => '0', 'variacion' => '35 %'],
        'XXX' => ['label' => 'Los códigos asignados para las transacciones en que intervenga ninguna moneda', 'decimales' => '0', 'variacion' => null],
        'YER' => ['label' => 'Rial yemení', 'decimales' => '2', 'variacion' => '35 %'],
        'ZAR' => ['label' => 'Rand', 'decimales' => '2', 'variacion' => '54 %'],
        'ZMW' => ['label' => 'Kwacha zambiano', 'decimales' => '2', 'variacion' => '35 %'],
        'ZWL' => ['label' => 'Zimbabwe Dólar', 'decimales' => '2', 'variacion' => '35 %'],
    ];
}