<?php

namespace Sat\Catalogos\Cfdi;

class Pais extends \Sat\Catalogos\Base {
    protected static $db = [
        'ABW' => ['label' => 'Aruba', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AFG' => ['label' => 'Afganistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AGO' => ['label' => 'Angola', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AIA' => ['label' => 'Anguila', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ALA' => ['label' => 'Islas Åland', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ALB' => ['label' => 'Albania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AND' => ['label' => 'Andorra', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ARE' => ['label' => 'Emiratos Árabes Unidos (Los)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ARG' => ['label' => 'Argentina', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ARM' => ['label' => 'Armenia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ASM' => ['label' => 'Samoa Americana', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ATA' => ['label' => 'Antártida', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ATF' => ['label' => 'Territorios Australes Franceses (los)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ATG' => ['label' => 'Antigua y Barbuda', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AUS' => ['label' => 'Australia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'AUT' => ['label' => 'Austria', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'AZE' => ['label' => 'Azerbaiyán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BDI' => ['label' => 'Burundi', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BEL' => ['label' => 'Bélgica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'BEN' => ['label' => 'Benín', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BES' => ['label' => 'Bonaire, San Eustaquio y Saba', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BFA' => ['label' => 'Burkina Faso', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BGD' => ['label' => 'Bangladés', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BGR' => ['label' => 'Bulgaria', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'BHR' => ['label' => 'Baréin', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BHS' => ['label' => 'Bahamas (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BIH' => ['label' => 'Bosnia y Herzegovina', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BLM' => ['label' => 'San Bartolomé', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BLR' => ['label' => 'Bielorrusia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BLZ' => ['label' => 'Belice', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BMU' => ['label' => 'Bermudas', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BOL' => ['label' => 'Bolivia, Estado Plurinacional de', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BRA' => ['label' => 'Brasil', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BRB' => ['label' => 'Barbados', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BRN' => ['label' => 'Brunéi Darussalam', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BTN' => ['label' => 'Bután', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BVT' => ['label' => 'Isla Bouvet', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'BWA' => ['label' => 'Botsuana', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CAF' => ['label' => 'República Centroafricana (la)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CAN' => ['label' => 'Canadá', 'patron_cp' => '[A-Z][0-9][A-Z] [0-9][A-Z][0-9]', 'patron_registro' => '[0-9]{9}', 'validacion_registro' => '', 'agrupacion' => 'TLCAN'],
        'CCK' => ['label' => 'Islas Cocos (Keeling)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CHE' => ['label' => 'Suiza', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CHL' => ['label' => 'Chile', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CHN' => ['label' => 'China', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CIV' => ['label' => 'Côte d\'Ivoire', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CMR' => ['label' => 'Camerún', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'COD' => ['label' => 'Congo (la República Democrática del)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'COG' => ['label' => 'Congo', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'COK' => ['label' => 'Islas Cook (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'COL' => ['label' => 'Colombia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'COM' => ['label' => 'Comoras', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CPV' => ['label' => 'Cabo Verde', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CRI' => ['label' => 'Costa Rica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CUB' => ['label' => 'Cuba', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CUW' => ['label' => 'Curaçao', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CXR' => ['label' => 'Isla de Navidad', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CYM' => ['label' => 'Islas Caimán (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'CYP' => ['label' => 'Chipre', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'CZE' => ['label' => 'República Checa (la)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'DEU' => ['label' => 'Alemania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'DJI' => ['label' => 'Yibuti', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'DMA' => ['label' => 'Dominica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'DNK' => ['label' => 'Dinamarca', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'DOM' => ['label' => 'República Dominicana (la)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'DZA' => ['label' => 'Argelia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ECU' => ['label' => 'Ecuador', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'EGY' => ['label' => 'Egipto', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ERI' => ['label' => 'Eritrea', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ESH' => ['label' => 'Sahara Occidental', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ESP' => ['label' => 'España', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'EST' => ['label' => 'Estonia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'ETH' => ['label' => 'Etiopía', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'FIN' => ['label' => 'Finlandia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'FJI' => ['label' => 'Fiyi', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'FLK' => ['label' => 'Islas Malvinas [Falkland] (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'FRA' => ['label' => 'Francia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'FRO' => ['label' => 'Islas Feroe (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'FSM' => ['label' => 'Micronesia (los Estados Federados de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GAB' => ['label' => 'Gabón', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GBR' => ['label' => 'Reino Unido (el)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'GEO' => ['label' => 'Georgia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GGY' => ['label' => 'Guernsey', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GHA' => ['label' => 'Ghana', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GIB' => ['label' => 'Gibraltar', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GIN' => ['label' => 'Guinea', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GLP' => ['label' => 'Guadalupe', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GMB' => ['label' => 'Gambia (La)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GNB' => ['label' => 'Guinea-Bisáu', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GNQ' => ['label' => 'Guinea Ecuatorial', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GRC' => ['label' => 'Grecia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'GRD' => ['label' => 'Granada', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GRL' => ['label' => 'Groenlandia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GTM' => ['label' => 'Guatemala', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GUF' => ['label' => 'Guayana Francesa', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GUM' => ['label' => 'Guam', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'GUY' => ['label' => 'Guyana', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'HKG' => ['label' => 'Hong Kong', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'HMD' => ['label' => 'Isla Heard e Islas McDonald', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'HND' => ['label' => 'Honduras', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'HRV' => ['label' => 'Croacia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'HTI' => ['label' => 'Haití', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'HUN' => ['label' => 'Hungría', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'IDN' => ['label' => 'Indonesia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'IMN' => ['label' => 'Isla de Man', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'IND' => ['label' => 'India', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'IOT' => ['label' => 'Territorio Británico del Océano Índico (el)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'IRL' => ['label' => 'Irlanda', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'IRN' => ['label' => 'Irán (la República Islámica de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'IRQ' => ['label' => 'Irak', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ISL' => ['label' => 'Islandia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ISR' => ['label' => 'Israel', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ITA' => ['label' => 'Italia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'JAM' => ['label' => 'Jamaica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'JEY' => ['label' => 'Jersey', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'JOR' => ['label' => 'Jordania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'JPN' => ['label' => 'Japón', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KAZ' => ['label' => 'Kazajistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KEN' => ['label' => 'Kenia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KGZ' => ['label' => 'Kirguistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KHM' => ['label' => 'Camboya', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KIR' => ['label' => 'Kiribati', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KNA' => ['label' => 'San Cristóbal y Nieves', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KOR' => ['label' => 'Corea (la República de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'KWT' => ['label' => 'Kuwait', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LAO' => ['label' => 'Lao, (la) República Democrática Popular', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LBN' => ['label' => 'Líbano', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LBR' => ['label' => 'Liberia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LBY' => ['label' => 'Libia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LCA' => ['label' => 'Santa Lucía', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LIE' => ['label' => 'Liechtenstein', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LKA' => ['label' => 'Sri Lanka', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LSO' => ['label' => 'Lesoto', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'LTU' => ['label' => 'Lituania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'LUX' => ['label' => 'Luxemburgo', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'LVA' => ['label' => 'Letonia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'MAC' => ['label' => 'Macao', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MAF' => ['label' => 'San Martín (parte francesa)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MAR' => ['label' => 'Marruecos', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MCO' => ['label' => 'Mónaco', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MDA' => ['label' => 'Moldavia (la República de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MDG' => ['label' => 'Madagascar', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MDV' => ['label' => 'Maldivas', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MEX' => ['label' => 'México', 'patron_cp' => '[0-9]{5}', 'patron_registro' => '\"[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]\"', 'validacion_registro' => 'Lista del SAT', 'agrupacion' => 'TLCAN'],
        'MHL' => ['label' => 'Islas Marshall (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MKD' => ['label' => 'Macedonia (la antigua República Yugoslava de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MLI' => ['label' => 'Malí', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MLT' => ['label' => 'Malta', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'MMR' => ['label' => 'Myanmar', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MNE' => ['label' => 'Montenegro', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MNG' => ['label' => 'Mongolia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MNP' => ['label' => 'Islas Marianas del Norte (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MOZ' => ['label' => 'Mozambique', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MRT' => ['label' => 'Mauritania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MSR' => ['label' => 'Montserrat', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MTQ' => ['label' => 'Martinica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MUS' => ['label' => 'Mauricio', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MWI' => ['label' => 'Malaui', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MYS' => ['label' => 'Malasia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'MYT' => ['label' => 'Mayotte', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NAM' => ['label' => 'Namibia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NCL' => ['label' => 'Nueva Caledonia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NER' => ['label' => 'Níger (el)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NFK' => ['label' => 'Isla Norfolk', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NGA' => ['label' => 'Nigeria', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NIC' => ['label' => 'Nicaragua', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NIU' => ['label' => 'Niue', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NLD' => ['label' => 'Países Bajos (los)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'NOR' => ['label' => 'Noruega', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NPL' => ['label' => 'Nepal', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NRU' => ['label' => 'Nauru', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'NZL' => ['label' => 'Nueva Zelanda', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'OMN' => ['label' => 'Omán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PAK' => ['label' => 'Pakistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PAN' => ['label' => 'Panamá', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PCN' => ['label' => 'Pitcairn', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PER' => ['label' => 'Perú', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PHL' => ['label' => 'Filipinas (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PLW' => ['label' => 'Palaos', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PNG' => ['label' => 'Papúa Nueva Guinea', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'POL' => ['label' => 'Polonia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'PRI' => ['label' => 'Puerto Rico', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PRK' => ['label' => 'Corea (la República Democrática Popular de)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PRT' => ['label' => 'Portugal', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'PRY' => ['label' => 'Paraguay', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PSE' => ['label' => 'Palestina, Estado de', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'PYF' => ['label' => 'Polinesia Francesa', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'QAT' => ['label' => 'Catar', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'REU' => ['label' => 'Reunión', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ROU' => ['label' => 'Rumania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'RUS' => ['label' => 'Rusia, (la) Federación de', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'RWA' => ['label' => 'Ruanda', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SAU' => ['label' => 'Arabia Saudita', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SDN' => ['label' => 'Sudán (el)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SEN' => ['label' => 'Senegal', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SGP' => ['label' => 'Singapur', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SGS' => ['label' => 'Georgia del sur y las islas sandwich del sur', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SHN' => ['label' => 'Santa Helena, Ascensión y Tristán de Acuña', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SJM' => ['label' => 'Svalbard y Jan Mayen', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SLB' => ['label' => 'Islas Salomón (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SLE' => ['label' => 'Sierra leona', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SLV' => ['label' => 'El Salvador', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SMR' => ['label' => 'San Marino', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SOM' => ['label' => 'Somalia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SPM' => ['label' => 'San Pedro y Miquelón', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SRB' => ['label' => 'Serbia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SSD' => ['label' => 'Sudán del Sur', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'STP' => ['label' => 'Santo Tomé y Príncipe', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SUR' => ['label' => 'Surinam', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SVK' => ['label' => 'Eslovaquia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'SVN' => ['label' => 'Eslovenia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'SWE' => ['label' => 'Suecia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => 'Unión Europea'],
        'SWZ' => ['label' => 'Suazilandia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SXM' => ['label' => 'Sint Maarten (parte holandesa)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SYC' => ['label' => 'Seychelles', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'SYR' => ['label' => 'Siria, (la) República Árabe', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TCA' => ['label' => 'Islas Turcas y Caicos (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TCD' => ['label' => 'Chad', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TGO' => ['label' => 'Togo', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'THA' => ['label' => 'Tailandia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TJK' => ['label' => 'Tayikistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TKL' => ['label' => 'Tokelau', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TKM' => ['label' => 'Turkmenistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TLS' => ['label' => 'Timor-Leste', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TON' => ['label' => 'Tonga', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TTO' => ['label' => 'Trinidad y Tobago', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TUN' => ['label' => 'Túnez', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TUR' => ['label' => 'Turquía', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TUV' => ['label' => 'Tuvalu', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TWN' => ['label' => 'Taiwán (Provincia de China)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'TZA' => ['label' => 'Tanzania, República Unida de', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'UGA' => ['label' => 'Uganda', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'UKR' => ['label' => 'Ucrania', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'UMI' => ['label' => 'Islas de Ultramar Menores de Estados Unidos (las)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'URY' => ['label' => 'Uruguay', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'USA' => ['label' => 'Estados Unidos (los)', 'patron_cp' => '[0-9]{5}(-[0-9]{4})?', 'patron_registro' => '[0-9]{9}', 'validacion_registro' => '', 'agrupacion' => 'TLCAN'],
        'UZB' => ['label' => 'Uzbekistán', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VAT' => ['label' => 'Santa Sede[Estado de la Ciudad del Vaticano] (la)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VCT' => ['label' => 'San Vicente y las Granadinas', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VEN' => ['label' => 'Venezuela, República Bolivariana de', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VGB' => ['label' => 'Islas Vírgenes (Británicas)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VIR' => ['label' => 'Islas Vírgenes (EE.UU.)', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VNM' => ['label' => 'Viet Nam', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'VUT' => ['label' => 'Vanuatu', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'WLF' => ['label' => 'Wallis y Futuna', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'WSM' => ['label' => 'Samoa', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'YEM' => ['label' => 'Yemen', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ZAF' => ['label' => 'Sudáfrica', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ZMB' => ['label' => 'Zambia', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ZWE' => ['label' => 'Zimbabue', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
        'ZZZ' => ['label' => 'Países no declarados', 'patron_cp' => '', 'patron_registro' => '', 'validacion_registro' => '', 'agrupacion' => ''],
    ];
}