<?php

namespace Sat\Catalogos\Cfdi;

class FormaPago extends \Sat\Catalogos\Base {
    protected static $db = [
        '01' => ['label' => 'Efectivo', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '02' => ['label' => 'Cheque nominativo', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{11}|[0-9]{18}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'Si el RFC del emisor de la cuenta ordenante es XEXX010101000, este campo es obligatorio.'],
        '03' => ['label' => 'Transferencia electrónica de fondos', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{10}|[0-9]{16}|[0-9]{18}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10}|[0-9]{18}', 'tipo_cadena_pago' => 'Opcional', 'banco_ordenante' => 'Si el RFC del emisor de la cuenta ordenante es XEXX010101000, este campo es obligatorio.'],
        '04' => ['label' => 'Tarjeta de crédito', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{16}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'Si el RFC del emisor de la cuenta ordenante es XEXX010101000, este campo es obligatorio.'],
        '05' => ['label' => 'Monedero electrónico', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '06' => ['label' => 'Dinero electrónico', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{10}', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '08' => ['label' => 'Vales de despensa', 'bancarizado' => 'NO', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '12' => ['label' => 'Dación en pago', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '13' => ['label' => 'Pago por subrogación', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '14' => ['label' => 'Pago por consignación', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '15' => ['label' => 'Condonación', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '17' => ['label' => 'Compensación', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '23' => ['label' => 'Novación', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '24' => ['label' => 'Confusión', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '25' => ['label' => 'Remisión de deuda', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '26' => ['label' => 'Prescripción o caducidad', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '27' => ['label' => 'A satisfacción del acreedor', 'bancarizado' => 'No', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'No', 'cuenta_ordenante' => 'No', 'patron_cuenta_ordenante' => 'No', 'rfc_beneficiario' => 'No', 'cuenta_beneficiario' => 'No', 'patron_beneficiario' => 'No', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'No'],
        '28' => ['label' => 'Tarjeta de débito', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{16}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'Si el RFC del emisor de la cuenta ordenante es XEXX010101000, este campo es obligatorio.'],
        '29' => ['label' => 'Tarjeta de servicios', 'bancarizado' => 'Sí', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => '[0-9]{15,16}', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => '[0-9]{10,11}|[0-9]{15,16}|[0-9]{18}|[A-Z0-9_]{10,50}', 'tipo_cadena_pago' => 'No', 'banco_ordenante' => 'Si el RFC del emisor de la cuenta ordenante es XEXX010101000, este campo es obligatorio.'],
        '99' => ['label' => 'Por definir', 'bancarizado' => 'Opcional', 'numero_operacion' => 'Opcional', 'rfc_cuenta_ordenante' => 'Opcional', 'cuenta_ordenante' => 'Opcional', 'patron_cuenta_ordenante' => 'Opcional', 'rfc_beneficiario' => 'Opcional', 'cuenta_beneficiario' => 'Opcional', 'patron_beneficiario' => 'Opcional', 'tipo_cadena_pago' => 'Opcional', 'banco_ordenante' => 'Opcional'],
    ];
}